dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - python -m pip install --upgrade pip
  - python setup.py install
  - python -m pip install -r requirements_test.txt
before_script:
  - export PYTHONPATH=`pwd`
script:
  - pytest --cov ga4gh/ --cov-report=term-missing tests/
after_success:
  - coveralls
